apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd3-api
  labels:
    app: sd3-api
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sd3-api
            port:
              number: 8000
