---
# Cloud credentials are a sensitive information
# clouds_credentials:
# database:
#   # HA mode is based on patroni, for now disabled while clarifying of the
#   # deployment issues (not always proper connectivity between nodes)
#   databases:
#     - name: grafana
#       users:
#         - name: grafana
#     - name: apimon
#       users:
#         - name: apimon
#     - name: status_dashboard
#       users:
#         - name: sdb

grafana:
  dashboards:
    - name: main
      repo_url: https://github.com/stackmon/apimon-tests.git
      repo_ref: main
      path: dashboards/grafana

# What we monitor and which credentials to use from every monitoring location
# (zone)
environments:
  # NOTE: not allowed to use same cloud names in same zone for different envs
  - name: production_eu-de
    env:
      OS_CLOUD: production_eu-de
    monitoring_zones:
      - name: eu-de
        clouds:
          - name: production_eu-de
            ref: probes-de1  # we want to monitor DE from DE
          - name: swift
            ref: swift1
      - name: eu-nl
        clouds:
          - name: production_eu-de
            ref: probes-de2  # we want to monitor DE from NL
          - name: swift
            ref: swift1
  - name: production_eu-nl
    env:
      OS_CLOUD: production_eu-nl
    monitoring_zones:
      - name: eu-de
        clouds:
          - name: production_eu-nl
            ref: probes-nl1  # we want to monitor NL from DE
          - name: swift
            ref: swift1
      - name: eu-nl
        clouds:
          - name: production_eu-nl
            ref: probes-nl2  # we want to monitor NL from NL
          - name: swift
            ref: swift1
  - name: hybrid_eu-ch2
    env:
      OS_CLOUD: hybrid_eu-ch2
    monitoring_zones:
      - name: eu-de
        clouds:
          - name: hybrid_eu-ch2
            ref: probes-ch2-from-de  # we want to monitor CH2 from DE
          - name: swift
            ref: swift1
      - name: eu-nl
        clouds:
          - name: hybrid_eu-ch2
            ref: probes-ch2-from-nl  # we want to monitor CH2 from NL
          - name: swift
            ref: swift1

matrix:
  # Mapping of environments to test projects
  # Regular apimon project in env ext
  - env: production_eu-de
    monitoring_zone: eu-de
    # TODO: placing db_url here feels questionable
    # db_url or db_entry as ref to database.databases
    db_entry: apimon.apimon
    plugins:
      - name: apimon
        schedulers_inventory_group_name: schedulers
        executors_inventory_group_name: executors
        #epmons_inventory_group_name: epmons
        tests_project: apimon
        tasks:
          - scenario1_token.yaml
      - name: epmon
        epmon_inventory_group_name: epmon_de
        cloud_name: production_eu-de # env in zone has few creds. We need to pick one
        config_elements:
          - antiddos
          - antiddos_skip_bad_type
          - as
          - as_skip_v1
          - bms_skip
          - cce_skip_unver
          - cce
          - ces
          - ces_skip_v1
          - compute
          - css
          - cts_skip_unver
          - cts
          - dataarts
          - data_protect_skip
          - database_skip
          - dcs
          - dcs_skip_v1
          - dds
          - deh
          - dis_skip_unver
          - dis
          - dli
          - dms
          - dms_skip_v2
          - dns
          - dws
          - dws_skip_v1
          - identity
          - image
          - kms_skip_unver
          - kms
          - mrs
          - nat
          - network
          - object_skip
          - object_store
          - orchestration
          - rds_skip_unver
          - rds_skip_v1
          - rds
          - sdrs
          - sfsturbo
          - share
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume
  - env: production_eu-nl
    monitoring_zone: eu-de
    db_entry: apimon.apimon
    plugins:
      - name: apimon
        schedulers_inventory_group_name: schedulers
        executors_inventory_group_name: executors
        #epmons_inventory_group_name: epmons
        tests_project: apimon
        tasks:
          - scenario1_token.yaml
      - name: epmon
        epmon_inventory_group_name: epmon_de
        cloud_name: production_eu-nl # env in zone has few creds. We need to pick one
        config_elements:
          - antiddos
          - antiddos_skip_bad_type
          - as
          - as_skip_v1
          - bms_skip
          - cce_skip_unver
          - cce
          - ces
          - ces_skip_v1
          - compute
          - css
          - cts_skip_unver
          - cts
          - data_protect_skip
          - database_skip
          - dcs
          - dcs_skip_v1
          - dds
          - deh
          - dis_skip_unver
          - dis
          - dms
          - dms_skip_v2
          - dns
          - dws
          - dws_skip_v1
          - identity
          - image
          - kms_skip_unver
          - kms
          - mrs
          - nat
          - network
          - object_skip
          - object_store
          - orchestration
          - rds_skip_unver
          - rds_skip_v1
          - rds
          - sdrs
          - sfsturbo
          - share
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume
  - env: production_eu-de
    monitoring_zone: eu-nl
    # TODO: placing db_url here feels questionable
    # db_url or db_entry as ref to database.databases
    db_entry: apimon.apimon
    plugins:
      - name: epmon
        epmon_inventory_group_name: epmon_nl
        cloud_name: production_eu-de # env in zone has few creds. We need to pick one
        config_elements:
          - antiddos
          - antiddos_skip_bad_type
          - as
          - as_skip_v1
          - bms_skip
          - cce_skip_unver
          - cce
          - ces
          - ces_skip_v1
          - compute
          - css
          - cts_skip_unver
          - cts
          - dataarts
          - data_protect_skip
          - database_skip
          - dcs
          - dcs_skip_v1
          - dds
          - deh
          - dis_skip_unver
          - dis
          - dli
          - dms
          - dms_skip_v2
          - dns
          - dws
          - dws_skip_v1
          - identity
          - image
          - kms_skip_unver
          - kms
          - mrs
          - nat
          - network
          - object_skip
          - object_store
          - orchestration
          - rds_skip_unver
          - rds_skip_v1
          - rds
          - sdrs
          - sfsturbo
          - share
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume
  - env: production_eu-nl
    monitoring_zone: eu-nl
    db_entry: apimon.apimon
    plugins:
      - name: epmon
        epmon_inventory_group_name: epmon_nl
        cloud_name: production_eu-nl # env in zone has few creds. We need to pick one
        config_elements:
          - antiddos
          - antiddos_skip_bad_type
          - as
          - as_skip_v1
          - bms_skip
          - cce_skip_unver
          - cce
          - ces
          - ces_skip_v1
          - compute
          - css
          - cts_skip_unver
          - cts
          - data_protect_skip
          - database_skip
          - dcs
          - dcs_skip_v1
          - dds
          - deh
          - dis_skip_unver
          - dis
          - dms
          - dms_skip_v2
          - dns
          - dws
          - dws_skip_v1
          - identity
          - image
          - kms_skip_unver
          - kms
          - mrs
          - nat
          - network
          - object_skip
          - object_store
          - orchestration
          - rds_skip_unver
          - rds_skip_v1
          - rds
          - sdrs
          - sfsturbo
          - share
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume
  - env: hybrid_eu-ch2
    monitoring_zone: eu-de
    db_entry: apimon.apimon
    plugins:
      - name: epmon
        epmon_inventory_group_name: epmon_de
        cloud_name: hybrid_eu-ch2 # env in zone has few creds. We need to pick one
        config_elements:
          - as_swiss
          - cce
          - ces
          - ces_skip_v1
          - compute
          - cts_skip_unver
          - cts_skip_v2
          - cts_v3
          - dcaas
          - deh
          - dns_private_only
          - identity
          - image
          - kms_skip_unver
          - kms
          - nat
          - network
          - object_skip
          - rds
          - sdrs
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume_no_backups
  - env: hybrid_eu-ch2
    monitoring_zone: eu-nl
    db_entry: apimon.apimon
    plugins:
      - name: epmon
        epmon_inventory_group_name: epmon_nl
        cloud_name: hybrid_eu-ch2 # env in zone has few creds. We need to pick one
        config_elements:
          - as_swiss
          - cce
          - ces
          - ces_skip_v1
          - compute
          - cts_skip_unver
          - cts_skip_v2
          - cts_v3
          - dcaas
          - deh
          - dns_private_only
          - identity
          - image
          - kms_skip_unver
          - kms
          - nat
          - network
          - object_skip
          - rds
          - sdrs
          - smn
          - smn_skip_v2
          - volume_skip_v2
          - volume_no_backups

metrics_processor:
  - name: prod
    kube_context: cloudmon-de
    kube_namespace: stackmon
    domain_name: metrics.cloudmon.eco.tsi-dev.otc-service.com
    environments:
      - name: "production_eu-de"
        attributes:
          region: "EU-DE"
      - name: "production_eu-nl"
        attributes:
          region: "EU-NL"
    status_dashboard_instance_name: "prod"
    kustomization:
      extra_files:
        - mp-prod/conf.d/flag_metrics.yaml
        - mp-prod/conf.d/health_metrics.yaml
        - mp-prod/conf.d/metric_templates.yaml

      configMapGenerator:
        - name: metrics-processor-confd
          behavior: merge
          files:
            - flag_metrics.yaml=mp-prod/conf.d/flag_metrics.yaml
            - health_metrics.yaml=mp-prod/conf.d/health_metrics.yaml
            - metric_templates.yaml=mp-prod/conf.d/metric_templates.yaml

      images:
        - name: quay.io/stackmon/metrics-processor
          newTag: "change_11_latest"

      patches:
        - patch: |-
            - op: replace
              path: /spec/ingressClassName
              value: nginx
            - op: replace
              path: /spec/rules/0/host
              value: metrics.cloudmon.eco.tsi-dev.otc-service.com
            - op: replace
              path: /metadata/annotations
              value:
                cert-manager.io/cluster-issuer: letsencrypt-prod
            - op: replace
              path: /spec/tls
              value:
                - hosts:
                    - metrics.cloudmon.eco.tsi-dev.otc-service.com
                  secretName: metrics-processor-cert-prod
          target:
            group: networking.k8s.io
            kind: Ingress
            name: metrics-processor
            version: v1

  - name: hybrid-ch2_from_eu-de
    kube_context: cloudmon-de
    kube_namespace: stackmon-ch2
    domain_name: metrics-ch2.cloudmon.eco.tsi-dev.otc-service.com
    environments:
      - name: "hybrid_eu-ch2"
        attributes:
          region: "EU-CH2"
    status_dashboard_instance_name: "hybrid-ch2_from_eu-de"
    kustomization:
      extra_files:
        - mp-ch2/conf.d/flag_metrics.yaml
        - mp-ch2/conf.d/health_metrics.yaml
        - mp-ch2/conf.d/metric_templates.yaml

      configMapGenerator:
        - name: metrics-processor-confd
          behavior: merge
          files:
            - flag_metrics.yaml=mp-ch2/conf.d/flag_metrics.yaml
            - health_metrics.yaml=mp-ch2/conf.d/health_metrics.yaml
            - metric_templates.yaml=mp-ch2/conf.d/metric_templates.yaml

      images:
        - name: quay.io/stackmon/metrics-processor
          newTag: "change_11_latest"

      patches:
        - patch: |-
            - op: replace
              path: /spec/ingressClassName
              value: nginx
            - op: replace
              path: /spec/rules/0/host
              value: metrics-ch2.cloudmon.eco.tsi-dev.otc-service.com
            - op: replace
              path: /metadata/annotations
              value:
                cert-manager.io/cluster-issuer: letsencrypt-prod
            - op: replace
              path: /spec/tls
              value:
                - hosts:
                    - metrics-ch2.cloudmon.eco.tsi-dev.otc-service.com
                  secretName: metrics-processor-cert-prod
          target:
            group: networking.k8s.io
            kind: Ingress
            name: metrics-processor
            version: v1

monitoring_zones:  # Defining from where we are monitoring
  - name: eu-de
    graphite_group_name: graphite_eu_de
    statsd_group_name: statsd_eu_de
  - name: eu-nl
    graphite_group_name: graphite_eu_nl
    statsd_group_name: statsd_eu_nl
  - name: hybrid_eu-ch2
    graphite_group_name: graphite_eu_ch
    statsd_group_name: statsd_eu_ch

# Known CloudMon plugins with their basic settings
plugins:
  - name: apimon
    type: apimon
    scheduler_image: quay.io/opentelekomcloud/apimon:dev
    executor_image: quay.io/opentelekomcloud/apimon:dev
      # epmon_image: quay.io/opentelekomcloud/apimon:dev
    tests_projects:
      - name: apimon
        repo_url: https://github.com/stackmon/apimon-tests
        repo_ref: main
        exec_cmd: ansible-playbook -i inventory/production %s -vvv
        scenarios_location: playbooks
        grafana_dashboards_location: dashboards
  - name: epmon
    type: epmon
    image: quay.io/stackmon/apimon:change_45_latest
    config: epmon/config.yaml
  - name: lb
    type: general
    image: quay.io/opentelekomcloud/cloudmon-plugin-lb
    init_image: quay.io/opentelekomcloud/cloudmon-plugin-lb-init

status_dashboard:
  - name: prod
    kube_context: cloudmon-de
    kube_namespace: stackmon
    domain_name: status.cloudmon.eco.tsi-dev.otc-service.com
    kustomization:
      extra_files:
        - sdb_prod/catalog.yaml

      images:
        - name: quay.io/opentelekomcloud/stackmon-status-dashboard
          newName: quay.io/opentelekomcloud/otc-status-dashboard
          newTag: "change_21_latest"
      patches:
        - patch: |-
            - op: replace
              path: /spec/ingressClassName
              value: nginx
            - op: replace
              path: /spec/rules/0/host
              value: status.cloudmon.eco.tsi-dev.otc-service.com
            - op: add
              path: /spec/rules/1/host
              value: status-beta.otc-service.com
            - op: replace
              path: /metadata/annotations
              value:
                cert-manager.io/cluster-issuer: letsencrypt-prod
            - op: replace
              path: /spec/tls
              value:
                - hosts:
                    - status.cloudmon.eco.tsi-dev.otc-service.com
                    - status-beta.otc-service.com
                  secretName: sdb-cert-prod
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/affinity
              value: "cookie"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-name
              value: "route"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-max-age
              value: "7200"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-expires
              value: "7200"
          target:
            group: networking.k8s.io
            kind: Ingress
            name: status-dashboard
            version: v1
        - patch: |-
            - op: replace
              path: /spec/replicas
              value: 2
          target:
            group: apps/v1
            kind: Deployment
            name: status-dashboard
            version: v1

      configMapGenerator:
        - name: sdb-config
          files:
            - catalog.yaml=sdb_prod/catalog.yaml

  - name: hybrid-ch2_from_eu-de
    kube_context: cloudmon-de
    kube_namespace: stackmon-ch2
    domain_name: status-ch2.cloudmon.eco.tsi-dev.otc-service.com
    kustomization:
      extra_files:
        - sdb_ch2/catalog.yaml

      images:
        - name: quay.io/opentelekomcloud/stackmon-status-dashboard
          newName: quay.io/opentelekomcloud/otc-status-dashboard
          newTag: "change_16_latest"
      patches:
        - patch: |-
            - op: replace
              path: /spec/ingressClassName
              value: nginx
            - op: replace
              path: /spec/rules/0/host
              value: status-ch2.cloudmon.eco.tsi-dev.otc-service.com
            - op: replace
              path: /spec/rules/1/host
              value: status-beta-ch2.otc-service.com
            - op: replace
              path: /metadata/annotations
              value:
                cert-manager.io/cluster-issuer: letsencrypt-prod
            - op: replace
              path: /spec/tls
              value:
                - hosts:
                    - status-ch2.cloudmon.eco.tsi-dev.otc-service.com
                    - status-beta-ch2.otc-service.com
                  secretName: sdb-cert-prod
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/affinity
              value: "cookie"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-name
              value: "route"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-max-age
              value: "7200"
            - op: add
              path: /metadata/annotations/nginx.ingress.kubernetes.io/session-cookie-expires
              value: "7200"
          target:
            group: networking.k8s.io
            kind: Ingress
            name: status-dashboard
            version: v1
        - patch: |-
            - op: replace
              path: /spec/replicas
              value: 2
          target:
            group: apps/v1
            kind: Deployment
            name: status-dashboard
            version: v1

      configMapGenerator:
        - name: sdb-config
          files:
            - catalog.yaml=sdb_ch2/catalog.yaml
