apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd3-frontend-ingress
  labels:
    app: sd3-frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sd3-frontend.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sd3-frontend
                port:
                  number: 80
