apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: status-dashboard

images:
  - name: sd3-frontend
    newName: quay.io/stackmon/status-dashboard-v3-front
    newTag: 1.0.1

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: sd3-frontend-ingress
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          location ~ ^/rss {
            return 301 https://api.status.otc-service.com$request_uri;
          }
    spec:
      rules:
        - host: status.otc-service.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: sd3-frontend
                  port:
                    number: 80

      tls:
      - hosts:
        - status.otc-service.com
        secretName: sd3-front-cert-prod
