name: Linters

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install tox
        run: pip install tox

      - name: Run linters
        run: tox -e linters
